apiVersion: apps/v1
kind: Deployment
metadata:
  name: rig-deployment
  labels:
    app: rig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rig
  template:
    metadata:
      labels:
        app: rig
    spec:
      containers:
        - name: rig
          image: {{rig.image}}
          ports:
            - containerPort: 9032
          resources:
            requests:
              memory: "4096Mi"
              cpu: "2000m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"

---
apiVersion: v1
kind: Service
metadata:
  name: rig
spec:
  selector:
    app: rig
  ports:
    - protocol: TCP
      port: 9032
      targetPort: 9032
